### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by oskarrough** [internet4000/realrealchat#5]
Should we also move this to netlify? Perhaps https://rcc.internet4000.com?

**Comment by oskarrough** [comment]
ping @hugurp :trollface:

**Comment by hugurp** [comment]
ja, not sur we need a subdomain, I'll put it on netlify

**Comment by hugurp** [comment]
```12:43:10 AM: npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.```

**Comment by hugurp** [comment]
actually, let's just write a new version using web sockets and vue/react?

**Comment by hugurp** [comment]
https://rrc.netlify.com/

**Comment by hugurp** [comment]
d965ede
